"use client";

import { useState } from "react";
import { Activity, ChevronDown, CircleHelp, Crown, Gauge, GitBranch, Play, RotateCcw, Settings2, Sparkles, Trophy, Users } from "lucide-react";

const files = ["a", "b", "c", "d", "e", "f", "g", "h"];
const ranks = [8, 7, 6, 5, 4, 3, 2, 1];
const pieces: Record<string, string> = { a8:"♜",b8:"♞",c8:"♝",d8:"♛",e8:"♚",f8:"♝",g8:"♞",h8:"♜",a7:"♟",b7:"♟",c7:"♟",d7:"♟",e7:"♟",f7:"♟",g7:"♟",h7:"♟",a2:"♙",b2:"♙",c2:"♙",d2:"♙",e2:"♙",f2:"♙",g2:"♙",h2:"♙",a1:"♖",b1:"♘",c1:"♗",d1:"♕",e1:"♔",f1:"♗",g1:"♘",h1:"♖",e4:"♟",d5:"♙",g5:"♘",c6:"♝" };
const moves = ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6"];

export default function Home() {
  const [selected, setSelected] = useState<string | null>(null);
  const [moveCount, setMoveCount] = useState(6);
  const [learning, setLearning] = useState(64);
  function handleSquare(square: string) { if (selected) { setMoveCount((count) => count + 1); setLearning((value) => Math.min(99, value + 1)); setSelected(null); } else if (pieces[square]) setSelected(square); }
  return <main className="app-shell"><div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <header className="topbar glass-panel"><div className="brand"><div className="brand-mark"><Crown size={18} strokeWidth={2.4} /></div><span>chessbot <em>lab</em></span></div><nav><button className="nav-active">Play</button><button>My bot</button><button>Leaderboard</button></nav><div className="top-actions"><button className="icon-button" aria-label="Help"><CircleHelp size={18} /></button><button className="profile"><span className="avatar">FE</span><span>furyengi</span><ChevronDown size={14} /></button></div></header>
    <section className="workspace"><aside className="left-rail"><div className="eyebrow">Your lab</div><div className="bot-card glass-panel active-card"><div className="bot-orb"><Sparkles size={18} /></div><div><strong>Nova</strong><span>learning from you</span></div><span className="live-dot" /></div><button className="rail-item"><Play size={17} />Practice</button><button className="rail-item"><GitBranch size={17} />Training log<span className="rail-count">12</span></button><button className="rail-item"><Trophy size={17} />Rankings</button><div className="rail-bottom"><button className="rail-item"><Settings2 size={17} />Settings</button><div className="sync-note"><span className="live-dot" />Syncing model memory</div></div></aside>
      <section className="play-area"><div className="section-heading"><div><div className="eyebrow">Practice session · game 13</div><h1>Teach Nova how you think.</h1></div><button className="ghost-button"><RotateCcw size={16} />New game</button></div><div className="board-wrap glass-panel"><div className="board-meta"><div className="opponent"><span className="mini-orb"><Sparkles size={13} /></span><span><strong>Nova</strong><small>Imitation bot · white</small></span></div><span className="turn-chip"><span className="live-dot" />Your turn</span></div><div className="chessboard" aria-label="Chess board">{ranks.flatMap((rank, row) => files.map((file, col) => { const square = `${file}${rank}`; const piece = pieces[square]; return <button key={square} aria-label={square} onClick={() => handleSquare(square)} className={`square ${(row + col) % 2 ? "dark-square" : "light-square"} ${selected === square ? "selected-square" : ""}`}>{piece && <span className={rank > 4 ? "black-piece" : "white-piece"}>{piece}</span>}{col === 0 && <i className="rank-label">{rank}</i>}{row === 7 && <i className="file-label">{file}</i>}</button>; }))}</div><div className="board-footer"><span><span className="key-dot" /> Nova is watching your patterns</span><span>{Math.floor(moveCount / 2)}:{String(moveCount % 2).padStart(2, "0")} <span className="clock-dot" /></span></div></div><div className="moves-panel glass-panel"><div className="panel-title"><span>Game record</span><small>{moveCount} moves</small></div><div className="move-list">{moves.map((move, index) => <div className="move-row" key={move}><span>{index + 1}.</span><b>{move}</b>{index === moves.length - 1 && <em>last move</em>}</div>)}</div></div></section>
      <aside className="right-rail"><div className="eyebrow">Nova’s memory</div><div className="memory-card glass-panel"><div className="memory-header"><div><strong>Style profile</strong><span>Updated just now</span></div><Activity size={18} /></div><div className="memory-stat"><div><span>Confidence</span><strong>{learning}%</strong></div><div className="progress"><span style={{ width: `${learning}%` }} /></div></div><div className="trait"><span className="trait-icon blue"><Gauge size={16} /></span><div><strong>Patient builder</strong><span>Prefers quiet development</span></div><b>+12%</b></div><div className="trait"><span className="trait-icon pink"><Sparkles size={16} /></span><div><strong>Early castle</strong><span>Protects the king by move 6</span></div><b>+8%</b></div></div><div className="eyebrow rank-label-heading">Your standing</div><div className="rank-card glass-panel"><div className="rank-line"><div className="rank-badge">#27</div><div><strong>Rising fast</strong><span>Top 8% this week</span></div><span className="rank-up">↗ 4</span></div><div className="rank-divider" /><div className="rank-metrics"><div><span>Bot rating</span><strong>1,248</strong></div><div><span>Training games</span><strong>12</strong></div></div></div><button className="match-button"><Users size={17} />Find a bot match</button></aside></section><footer className="footer-note"><span>Imitation mode</span><span>Nova learns from your moves, not from an engine.</span><span>v0.1 · private beta</span></footer></main>;
}
